### ISSUE TITLE
Prep for npm publish.

### ISSUE THREAD

**Issue by jdalton** [jdalton/docdown#22]
In prepping for publishing to npm I'll be lowering the version to 0.1.0 since this hasn't really been hammered on in JS land yet.

**Comment by phated** [comment]
can't publish as docdown, someone else has the name

**Comment by jdalton** [comment]
Bikeshed time!

**Comment by jdalton** [comment]
doc-dynasty, now your turn. go!

**Comment by stockholmux** [comment]
docaround
