### ISSUE TITLE
Add support for the @since tag.

### ISSUE THREAD

**Issue by jdalton** [jdalton/docdown#23]
Related to https://github.com/lodash/lodash/issues/993.

**Comment by phated** [comment]
:+1: really like that idea

**Comment by d10** [comment]
:+1: Not sure how we should display this though. Maybe next to the anchor links for each method?

**Comment by antch** [comment]
:+1:

**Comment by jetrii** [comment]
A million times :+1:

**Comment by jdalton** [comment]
A PR is worth a thousand :+1:'s : D

**Comment by antch** [comment]
I have this pretty much done. Any preference for location/exact output? Currently I just have it generating Markdown like the following between "Returns" and "Example":
```
#### Since
3.4.0
```

**Comment by antch** [comment]
FWIW I did do this but never got around to creating a PR; it's probably not correct at this point. But, for posterity: https://github.com/antch/docdown/commit/1c69f674275c9e976eeb62703208976e7a03f63b
