### ISSUE TITLE
Use doctrine to parse jsdoc

### ISSUE THREAD

**Issue by jdalton** [jdalton/docdown#26]
See [doctrine](https://www.npmjs.com/package/doctrine).

**Comment by d10** [comment]
:+1:!

**Comment by jdalton** [comment]
It looks like the issues with `doctrine` have been cleared up so we can totally use it.

**Comment by jdalton** [comment]
I'm working on adding this.

**Comment by DannyNemer** [comment]
Awesome!

**Comment by jfmengels** [comment]
Cool!

**Comment by jdalton** [comment]
It still needs some tweaks but it's on it's way.

**Comment by phated** [comment]
Let me know if you need any help on this.  I'm quite interested

**Comment by jfmengels** [comment]
I'll have to update the FP docs generation a bit with this. If I notice anything odd, I'll let you know.

**Comment by jdalton** [comment]
> I'll have to update the FP docs generation a bit with this. If I notice anything odd, I'll let you know.

Don't worry about that until we officially bump. Things are still baking at the moment.

**Comment by jfmengels** [comment]
:+1:
