### ISSUE TITLE
i find a bug about param parse....

### ISSUE THREAD

**Issue by xunuo** [jdalton/docdown#29]
/**
     * a bug about object param 
     * @param {object} args args is a object
     * @param {dom} args.target but can't parse the target in args
     * @type function
     */
    var _autoInit = function (args) {
        var dom = args.target,

i can't got args.target in result....

**Comment by xunuo** [comment]
and if the '@type function' missed, the param in the end will miss too

**Comment by xunuo** [comment]
i guess is the problem about 
  re = /@param\s+\{\(?([^})]+)\)?\}\s+(\[.+\]|[\w]+(?:\[.+\])?)\s+([\s\S]*?)(?=\@)/gim
in lib/entry.js and i modify it to :
  re = /@param\s+\{\(?([^})]+)\)?\}\s+(\[.+\]|[\.\w]+(?:\[.+\])?)\s+([\s\S]*?)(?=\@)/gim

it's ok....

**Comment by xunuo** [comment]
but can't support  the format like this:
  * @param array {object} The array to process.

**Comment by xunuo** [comment]
e.... i pulled a merge request :)

**Comment by jdalton** [comment]
Moved to #30.
