### ISSUE TITLE
Version number is not up to date

### ISSUE THREAD

**Issue by jfmengels** [jdalton/docdown#38]
The version number of the package is not up to date. On `npm`, it's at v0.4.0, while it's still 0.3 in the readme (I'd suggest simply removing the version number from the title) and more surprisingly in the package.json. Was it published on `npm` from a local machine without the repo being updated?

**Comment by jdalton** [comment]
I had just forgot to push a rebase. Fixed https://github.com/jdalton/docdown/commit/63136a3c100060d8d1762fdfbc7a52bab3d7ac15.
