### ISSUE TITLE
Support ES6/2015 class syntax

### ISSUE THREAD

**Issue by viveleroi** [jdalton/docdown#39]
Version 0.5.1 doesn't appear to support class syntax yet. I've just converted a library of mine and discovered the issue.

Running the latest version on the following example produces a pretty much empty markdown file.

```
export default class Test {
    /**
     * Test
     *
     * @param {string} msg Something to say
     * @return {boolean} Test boolean.
     */
    say(msg) {
        return false;
    }
}
```

Generated markdown:

```
# 

<!-- div class="toc-container" -->

<!-- /div -->

<!-- div class="doc-container" -->

<!-- /div -->

 [1]: # "Jump back to the TOC."
```

**Comment by jdalton** [comment]
Thanks!

**Comment by jdalton** [comment]
In the meantime you can specify the `@type Function` to signal to docdown the type.

**Comment by viveleroi** [comment]
My linter doesn't seem to accept `@type Function`, and while it does accept `@type {function}`, that doesn't seem to change docdown's output. I'll just wait for an updated build or tell npm to grab the latest master.
