### ISSUE TITLE
Issues with CR-LF line endings

### ISSUE THREAD

**Issue by HarrySarson** [jdalton/docdown#42]
Running docdown from bash for Windows (https://msdn.microsoft.com/commandline/wsl/about) resulted in extra new lines inserted into the documentation. What is only a single new line in the jsdoc comment and therefore should be ignored by docdown is treated as a double newline and so `<br>`'s are inserted into the markdown.

```markdown
<h3 id="itblmapiterable-iteratee_identity"><code>itbl.map(iterable, [iteratee=_.identity])</code></h3>
[&#x24C8;](https://github.com/harrysarson/itbl/blob/2.0.0/itbl.js#L569 "View in source") [&#x24C9;][1]

Creates a new iterable whose iterators will have values corresponding to the value
<br>
<br>
of the Iterator of the original iterable run through `iteratee`.
<br>
<br>
The iteratee is invoked with only one argument *(value)*.

#### Since
0.1.0
#### Arguments
1. `iterable` *(Iterable)*: Iterable to map values of.
2. `[iteratee=_.identity]` *(Function)*: Function to run each value though.

#### Returns
*(itbl)*: A new mapped iterable
```

Whilst this is quite a niche problem, any one using files created on windows and not properly converted would have the same problem.

**Comment by jdalton** [comment]
Are you proposing a patch or?

**Comment by jdalton** [comment]
You haven't shown me an expected result vs. an actual result. I see BR's not new lines. There's all kinds of issues with this issue report.

**Comment by jdalton** [comment]
Sorry for being a bit of a grouch there. 
We're supposed to be normalizing the `os.EOL` to `\n`. It looks like I missed a spot.
Can you test the latest master branch to see if it resolves your issue.

**Comment by HarrySarson** [comment]
The issue I am having is that because I am running the code from a bash shell `os.EOL === '\n'`. 

Therefore lines ending with `CR-LF` are not converted properly. I feel like docdown should be able to handle windows line endings even when running on linux.

**Comment by jdalton** [comment]
That's an interesting gotcha for the [BashOnWindows](https://github.com/Microsoft/BashOnWindows) folks for sure. Patched https://github.com/jdalton/docdown/commit/0fba8ceb3ffdbb9a64a13c4ca4f190a660640aaf.
