### ISSUE TITLE
Source link error/incompatibility with GitHub

### ISSUE THREAD

**Issue by viveleroi** [jdalton/docdown#46]
Using docdown 0.7.2, generated links to sections of the source code don't render as links when preceded by an html element (in github, at least).

For example, docdown generates the following markup for a function of mine:

```
<h3 id="available"><a href="#available">#</a>&nbsp;<code>available(full)</code></h3>
[&#x24C8;](https://github.com/helion3/inspire-tree/blob/master/src/tree.js#L243 "View in source") [&#x24C9;][1]
```

However, it renders as:

```
# available(full)

[Ⓢ](https://github.com/helion3/inspire-tree/blob/master/src/tree.js#L243 "View in source") [Ⓣ][1]
```

When I separate the elements with a new line, or when I remove the `h3`, the link renders:

```
Ⓢ [Ⓣ][1]
```

Here's the script I use which runs docdown and writes the resulting files: https://github.com/helion3/inspire-tree/blob/master/scripts/docs.js

You can see an example affected markdown file here: https://github.com/helion3/inspire-tree/blob/master/docs/tree.md

**Comment by jdalton** [comment]
It looks like GitHub changed something with their support. Would you be up for creating a PR?

**Comment by viveleroi** [comment]
I'm not really sure what the best solution would be. I'd rather not have to add new lines but don't have a lot of time to test other format choices that would still work.

**Comment by jdalton** [comment]
Moved to #47.
